spring.application.name=app-biblioteca-api

spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
 spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# Garante que a inicialização do DB ocorre após a config do datasource

spring.sql.init.mode.always=true
# Garante execução dos scripts de inicialização sejam executado nos mesmos banco de dado em memória

spring.jpa.show-sql=true
# Habilita a exibição de consultas no console