INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Java para web', 'Willian Santos', FALSE, NULL);
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Spring Boot na Pratica', 'Murillo Araujo', FALSE, NULL);
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Arquiterura REST', 'Luiz Eduardo', TRUE, '2026-03-01');
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('DeV Mobile', 'Jefferson Oliveira', FALSE,NULL);
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Chatbot', 'Henrique', TRUE, '2026-03-02');
